version: '3'
services:
  frontend:
    image: test-wiber-frontend
    ports:
      - "3000:3000"
  backend:
    image: test-wiber-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mongodb+srv://federicorouyere:mongo1234@prueba-cluster.cso4kl6.mongodb.net/